version: "2"
services:
  app:
    image: golang:latest
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "3000:3000"
    links:
      - db
      - redis
  db:
    image: postgres
    restart: always
    volumes:
      - ./1_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: dbserver
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      SERVICE_TAGS: redis-cluster:test
